-- sql/schema.sql

CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL,
    email VARCHAR2(100) NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE brands (
    brand_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_name VARCHAR2(100) NOT NULL,
    CONSTRAINT uq_brands_name UNIQUE (brand_name)
);

CREATE TABLE categories (
    category_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR2(100) NOT NULL,
    CONSTRAINT uq_categories_name UNIQUE (category_name)
);

CREATE TABLE products (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR2(150) NOT NULL,
    brand_id NUMBER NOT NULL,
    category_id NUMBER NOT NULL,
    price NUMBER(10,2) CHECK (price >= 0),
    release_date DATE,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_products_brand
        FOREIGN KEY (brand_id) REFERENCES brands(brand_id),
    CONSTRAINT fk_products_category
        FOREIGN KEY (category_id) REFERENCES categories(category_id)
);

CREATE TABLE reviews (
    review_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER NOT NULL,
    user_id NUMBER NOT NULL,
    rating NUMBER(1) NOT NULL,
    review_title VARCHAR2(150) NOT NULL,
    review_text CLOB,
    review_date DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT chk_reviews_rating CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT fk_reviews_product
        FOREIGN KEY (product_id) REFERENCES products(product_id),
    CONSTRAINT fk_reviews_user
        FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT uq_reviews_user_product UNIQUE (user_id, product_id)
);

CREATE TABLE review_votes (
    vote_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id NUMBER NOT NULL,
    user_id NUMBER NOT NULL,
    is_helpful CHAR(1) NOT NULL,
    vote_date DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT chk_review_votes_helpful CHECK (is_helpful IN ('Y', 'N')),
    CONSTRAINT fk_review_votes_review
        FOREIGN KEY (review_id) REFERENCES reviews(review_id),
    CONSTRAINT fk_review_votes_user
        FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT uq_review_votes_review_user UNIQUE (review_id, user_id)
);

CREATE TABLE review_images (
    image_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id NUMBER NOT NULL,
    image_url VARCHAR2(500) NOT NULL,
    uploaded_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_review_images_review
        FOREIGN KEY (review_id) REFERENCES reviews(review_id)
);